services:
  vnc:
    build: .
    container_name: linux_vnc
    ports:
      - "5901:5901"
      - "6901:6901"
    volumes:
      - ./config/vnc:/root/.vnc
    environment:
      - VNC_PASSWORD=secretpassword
      - USER=root           
    restart: unless-stopped
