version: '3.8'

services:
  vm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./disk:/disk
      - ./config:/config
    command: /config/vm-start.sh
    networks:
      - vm-network

  novnc:
    image: novnc/noVNC:latest
    ports:
      - "8080:80"
    volumes:
      - ./novnc:/usr/share/novnc
    networks:
      - vm-network
    depends_on:
      - vm

networks:
  vm-network:
    driver: bridge
