apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm-disk-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: vm-scripts
data:
  create-disk.sh: |
    #!/bin/bash
    echo "Создание диска..."
    # Добавь содержимое create-disk.sh
  download-file.sh: |
    #!/bin/bash
    echo "Скачивание файлов..."
    # Добавь содержимое download-file.sh
  vm-start.sh: |
    #!/bin/bash
    echo "Запуск ВМ..."
    # Добавь содержимое vm-start.sh

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vm
  template:
    metadata:
      labels:
        app: vm
    spec:
      containers:
        - name: vm
          image: your-dockerhub-username/your-vm-image:latest
          volumeMounts:
            - name: disk-volume
              mountPath: /disk
            - name: config-volume
              mountPath: /config
          command: ["/bin/bash", "-c"]
          args: ["chmod +x /config/*.sh && /config/vm-start.sh"]
      volumes:
        - name: disk-volume
          persistentVolumeClaim:
            claimName: vm-disk-pvc
        - name: config-volume
          configMap:
            name: vm-scripts
            defaultMode: 0775

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: novnc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: novnc
  template:
    metadata:
      labels:
        app: novnc
    spec:
      containers:
        - name: novnc
          image: theasp/novnc
          ports:
            - containerPort: 6080

---

apiVersion: v1
kind: Service
metadata:
  name: novnc-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 6080
      nodePort: 30080
  selector:
    app: novnc
